// Generated by tools/bundle-src.js from tools/art/*.js — do not edit by hand; edit the templates and rerun it.
const ARTSRC = (() => {
  const defs = {}, cache = {};
  const define = (k, fn) => { defs[k] = fn; };
  const require = (p) => { const k = p.replace(/\.js$/, '').replace(/^.*\//, ''); if (!cache[k]) { if (!defs[k]) throw new Error('art module ' + k); const module = { exports: {} }; cache[k] = module.exports; defs[k](module, module.exports, require); cache[k] = module.exports; } return cache[k]; };
define("lib", function (module, exports, require) {
// Scene-graph drawing helpers shared by every art template.
//
// Each helper returns a plain op object; templates compose ops in (nested) arrays and hand them to svg(w, h, ops),
// which returns a scene { w, h, ops }. A scene has two backends: toSvg(scene) serialises it to an SVG string for the
// art/ files, and the game's src/vec.js draws it straight onto a canvas every frame (that is how the characters
// animate: their templates are called with tweened parameters, see art/ANIMATION.md).
//
// Op fields mirror SVG attributes in camelCase: fill, stroke, strokeWidth, opacity, strokeLinecap, strokeLinejoin,
// strokeDasharray, transform (an SVG transform string such as 'translate(3 4) rotate(20 0 0) scale(1 -1)').
// A fill or stroke may be a colour string, 'none', or a gradient object from lin()/rad().
const path = (d, fill, o) => Object.assign({ t: 'path', d, fill }, o);
const ell = (cx, cy, rx, ry, fill, o) => Object.assign({ t: 'ell', cx, cy, rx, ry, fill }, o);
const circ = (cx, cy, r, fill, o) => Object.assign({ t: 'circ', cx, cy, r, fill }, o);
const rect = (x, y, w, h, fill, o) => Object.assign({ t: 'rect', x, y, w, h, fill }, o);
const line = (x1, y1, x2, y2, stroke, w, o) => Object.assign({ t: 'line', x1, y1, x2, y2, stroke, strokeWidth: w, strokeLinecap: 'round' }, o);
const stroke = (d, color, w, o) => Object.assign({ t: 'path', d, fill: 'none', stroke: color, strokeWidth: w, strokeLinecap: 'round', strokeLinejoin: 'round' }, o);
const text = (x, y, str, o) => Object.assign({ t: 'text', x, y, str }, o);
const g = (children, o) => Object.assign({ t: 'g', children: flat(children) }, o);
const flat = (a) => { const out = []; const walk = (v) => { if (v == null || v === false || v === '') return; if (Array.isArray(v)) v.forEach(walk); else out.push(v); }; walk(a); return out; };
const svg = (w, h, ops) => ({ w, h, ops: flat(ops) });
// gradients: stops are [offset, colour, alpha?]; coordinates are in the user space of the op that uses them
const lin = (id, x1, y1, x2, y2, stops) => ({ t: 'lin', id, x1, y1, x2, y2, stops });
const rad = (id, cx, cy, r, stops, fx, fy) => ({ t: 'rad', id, cx, cy, r, stops, fx, fy });
const rot = (deg, cx = 0, cy = 0) => `rotate(${num(deg)} ${num(cx)} ${num(cy)})`;
const tr = (x, y) => `translate(${num(x)} ${num(y)})`;
const num = (v) => (typeof v === 'number' ? +v.toFixed(3) : v);
// deterministic rng for scatter
const rng = (seed) => { let a = seed >>> 0; return () => { a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; };
// colour helpers
const hex = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
const toHex = (r, g2, b) => '#' + [r, g2, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');
const mix = (a, b, t) => { const A = hex(a), B = hex(b); return toHex(A[0] + (B[0] - A[0]) * t, A[1] + (B[1] - A[1]) * t, A[2] + (B[2] - A[2]) * t); };
const shade = (c, t) => (t < 0 ? mix(c, '#000000', -t) : mix(c, '#ffffff', t));
const lerp = (a, b, t) => a + (b - a) * t;
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
// a soft glow disc (radial gradient fading to transparent)
const glow = (cx, cy, r, color, a = 0.5) => circ(cx, cy, r, rad('gl', cx, cy, r, [[0, color, a], [1, color, 0]]));
// an eye with a glint; open 1 = round, 0 = a closed line; look shifts the pupil
const eye = (cx, cy, rx, ry, color = '#1a1526', glint = true, open = 1, look = 0) => {
  if (open < 0.12) return stroke(`M${num(cx - rx)} ${num(cy)} C${num(cx - rx * 0.4)} ${num(cy + ry * 0.45)} ${num(cx + rx * 0.4)} ${num(cy + ry * 0.45)} ${num(cx + rx)} ${num(cy)}`, color, Math.max(0.8, rx * 0.5));
  const px = cx + look * rx * 0.3;
  return [ell(px, cy, rx, ry * open, color), glint && open > 0.5 ? circ(px - rx * 0.35, cy - ry * open * 0.45, Math.max(0.5, rx * 0.3), '#ffffff') : null];
};
// a pupil-less glowing eye (hushed creatures); glowK scales the halo
const glowEye = (cx, cy, r, color, glowK = 1) => [circ(cx, cy, r * 1.8 * glowK, color, { opacity: 0.25 }), circ(cx, cy, r, color), circ(cx, cy, r * 0.45, '#ffffff', { opacity: 0.8 })];
// a smooth curve through points [{x,y},...] (Catmull-Rom converted to cubic Béziers)
const curve = (pts) => {
  if (pts.length < 2) return '';
  let d = `M${num(pts[0].x)} ${num(pts[0].y)}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[Math.max(0, i - 1)], p1 = pts[i], p2 = pts[i + 1], p3 = pts[Math.min(pts.length - 1, i + 2)];
    d += ` C${num(p1.x + (p2.x - p0.x) / 6)} ${num(p1.y + (p2.y - p0.y) / 6)} ${num(p2.x - (p3.x - p1.x) / 6)} ${num(p2.y - (p3.y - p1.y) / 6)} ${num(p2.x)} ${num(p2.y)}`;
  }
  return d;
};

// ---- SVG backend
const ATTR = { strokeWidth: 'stroke-width', strokeLinecap: 'stroke-linecap', strokeLinejoin: 'stroke-linejoin', strokeDasharray: 'stroke-dasharray', fontFamily: 'font-family', fontSize: 'font-size', fontWeight: 'font-weight', textAnchor: 'text-anchor', letterSpacing: 'letter-spacing', lengthAdjust: 'lengthAdjust', textLength: 'textLength' };
const SKIP = new Set(['t', 'd', 'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'w', 'h', 'x1', 'y1', 'x2', 'y2', 'children', 'str']);
function toSvg(scene) {
  const defs = []; const ids = new Map(); let n = 0;
  const gradId = (gr) => { if (ids.has(gr)) return ids.get(gr); const id = `${gr.id || 'g'}${++n}`; ids.set(gr, id);
    const stops = gr.stops.map(([o, c, a]) => `<stop offset="${o}" stop-color="${c}"${a !== undefined ? ` stop-opacity="${a}"` : ''}/>`).join('');
    defs.push(gr.t === 'lin' ? `<linearGradient id="${id}" x1="${num(gr.x1)}" y1="${num(gr.y1)}" x2="${num(gr.x2)}" y2="${num(gr.y2)}" gradientUnits="userSpaceOnUse">${stops}</linearGradient>`
      : `<radialGradient id="${id}" cx="${num(gr.cx)}" cy="${num(gr.cy)}" r="${num(gr.r)}"${gr.fx !== undefined ? ` fx="${num(gr.fx)}" fy="${num(gr.fy)}"` : ''} gradientUnits="userSpaceOnUse">${stops}</radialGradient>`);
    return id; };
  const paint = (v) => (v && typeof v === 'object' ? `url(#${gradId(v)})` : v);
  const attrs = (op) => { let s = ''; for (const k of Object.keys(op)) { if (SKIP.has(k)) continue; let v = op[k]; if (v === undefined || v === null || v === false) continue; if (k === 'fill' || k === 'stroke') v = paint(v); if (k === 'rx' && op.t === 'rect') {} s += ` ${ATTR[k] || k}="${num(v)}"`; } return s; };
  const el = (op) => {
    switch (op.t) {
      case 'g': return `<g${attrs(op)}>${op.children.map(el).join('')}</g>`;
      case 'path': return `<path d="${op.d}"${attrs(op)}/>`;
      case 'ell': return `<ellipse cx="${num(op.cx)}" cy="${num(op.cy)}" rx="${num(op.rx)}" ry="${num(op.ry)}"${attrs(op)}/>`;
      case 'circ': return `<circle cx="${num(op.cx)}" cy="${num(op.cy)}" r="${num(op.r)}"${attrs(op)}/>`;
      case 'rect': return `<rect x="${num(op.x)}" y="${num(op.y)}" width="${num(op.w)}" height="${num(op.h)}"${op.rx !== undefined ? ` rx="${num(op.rx)}"` : ''}${attrs(op)}/>`;
      case 'line': return `<line x1="${num(op.x1)}" y1="${num(op.y1)}" x2="${num(op.x2)}" y2="${num(op.y2)}"${attrs(op)}/>`;
      case 'text': return `<text x="${num(op.x)}" y="${num(op.y)}"${attrs(op)}>${op.str}</text>`;
    }
    return '';
  };
  const body = scene.ops.map(el).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${scene.w} ${scene.h}" width="${scene.w}" height="${scene.h}">${defs.length ? `<defs>${defs.join('')}</defs>` : ''}${body}</svg>`;
}
module.exports = { svg, toSvg, lin, rad, path, ell, circ, rect, line, stroke, text, g, flat, rot, tr, num, rng, mix, shade, lerp, clamp, glow, eye, glowEye, curve };

});
define("mote", function (module, exports, require) {
// Mote, the last spark: a small luminous spirit with ember-leaf ears and a wisp tail.
//
// This is the reference animated module (see art/ANIMATION.md). make(P, pup) is a pure drawing of the parameters,
// control(p, pup, info) turns the player's state into parameter targets every frame, springs do the in-betweens.
const L = require('./lib');
const { svg, lin, rad, path, ell, circ, stroke, g, rot, tr, eye, glow, curve, mix, clamp, lerp } = L;
const W = 36, H = 40, FX = 18, FY = 38; // feet anchor: bottom centre
const RUN = 165; // player run speed in world units (PHYS.RUN), for leaning and leg cycles
const SCALE = 0.62; // world units per template unit (ART_SCALE.mote), for feeding world velocities to the tail

const params = {
  lean: 0,            // body tilt in degrees, positive leans forward (Mote faces right)
  earL: -38, earR: -14, // ear angles, degrees from straight up; more negative sweeps them back
  earCurl: 0,         // 0 straight .. 1 tips bent back by wind
  legL: 0, legR: 0,   // leg swing in degrees (positive = forward)
  legTuck: 0,         // 0 standing .. 1 legs pulled up under the body
  eyeOpen: 1, look: 0, squint: 0, wide: 0,
  sx: 1, sy: 1, bob: 0, // squash / stretch about the feet, and body lift
  paw: 0, pawAng: -20, pawKind: 'none', // paw extension 0..1, its angle, and what it is doing: none | cling | strike | ember
  ember: 0,           // ember held in the paw, 0..1
  aura: 0, glow: 0.28, hurt: 0, sit: 0, cheek: 0.45,
};
// [stiffness, damping ratio] for the values that should overshoot and settle; the rest snap to their target
const springs = {
  lean: [260, 0.55], earL: [300, 0.42], earR: [300, 0.42], earCurl: [160, 0.7], legL: [520, 0.8], legR: [520, 0.8], legTuck: [320, 0.8],
  sx: [420, 0.5], sy: [420, 0.5], bob: [300, 0.6], paw: [560, 0.72], pawAng: [420, 0.7], look: [180, 0.8], aura: [60, 1], glow: [90, 1], hurt: [140, 1], sit: [120, 1], wide: [200, 0.8],
};
// stills exported to art/mote_<pose>.svg; they are also handy reference targets for control()
const poses = {
  idle: {},
  run1: { lean: 9, earL: -62, earR: -36, legL: -28, legR: 26 }, run2: { lean: 9, earL: -58, earR: -30, legL: -6, legR: 4, sy: 1.04 },
  run3: { lean: 9, earL: -66, earR: -40, legL: 26, legR: -28 }, run4: { lean: 9, earL: -60, earR: -34, legL: 4, legR: -6, sy: 1.04 },
  jump: { lean: 5, earL: -78, earR: -56, legL: -40, legR: -40, legTuck: 0.7, sx: 0.92, sy: 1.14 },
  fall: { lean: -3, earL: -8, earR: 14, legL: 14, legR: -10, wide: 1, sx: 1.04, sy: 0.96 },
  cling: { lean: -14, earL: -20, earR: 6, legL: 30, legR: 20, paw: 1, pawKind: 'cling', sx: 0.96, sy: 1.02 },
  dash: { lean: 22, earL: -92, earR: -74, earCurl: 1, legL: -30, legR: -30, legTuck: 0.5, squint: 1, sx: 1.28, sy: 0.74 },
  hurt: { lean: -10, earL: -30, earR: -46, legL: 20, legR: -20, squint: 1, hurt: 1, sx: 1.04, sy: 0.96 },
  sit: { earL: -48, earR: -30, eyeOpen: 0, sit: 1, sx: 1.08, sy: 0.9 },
  cast: { lean: 6, earL: -70, earR: -40, legL: -10, legR: 12, paw: 1, pawKind: 'ember', pawAng: -25, ember: 1 },
  strike: { lean: 14, earL: -84, earR: -60, legL: -22, legR: 18, squint: 1, paw: 1, pawKind: 'strike', pawAng: -18, sx: 1.06, sy: 0.96 },
  focus: { earL: -20, earR: 2, eyeOpen: 0, aura: 1, sx: 1.04, sy: 0.96 },
};
const TAIL_REST = [{ x: -3.5, y: 1 }, { x: -6.5, y: 3.5 }, { x: -8.5, y: 7 }];

function make(P, pup) {
  const bodyFill = lin('mb', 10, 10, 26, 36, [[0, mix('#fffaf0', '#ffb4b4', P.hurt)], [0.55, mix('#f4ecff', '#f0a0a0', P.hurt)], [1, mix('#d8ccff', '#e08c8c', P.hurt)]]);
  const earFill = lin('me', 0, 0, 0, -20, [[0, '#fff3dc'], [0.7, '#ffe2b0'], [1, '#ffb347']]);
  const core = rad('mc', 17, 21, 9, [[0, '#ffffff', 0.9], [1, '#ffffff', 0]]);
  // ears: leaf shapes whose tips bend with earCurl
  const ear = (deg, x, y) => { const c = P.earCurl * 5; return g([
    path(`M0 0 C-3.2 -6 ${-3.4 - c * 0.3} -13 ${-c} -20 C${3.4 - c * 0.6} -13 3.2 -6 0 0 Z`, earFill, { stroke: '#e8c690', strokeWidth: 0.7 }),
    stroke(`M0 -2 C0.4 -8 ${0.4 - c * 0.4} -13 ${-c * 0.9} -18`, '#f0c890', 0.6, { opacity: 0.7 }),
    circ(-c, -19, 1.6, '#ffd27a', { opacity: 0.55 }),
  ], { transform: `${tr(x, y)} ${rot(deg)}` }); };
  // tail: a wisp that trails the body (verlet chain when animated, its rest curve for the stills)
  const tailPts = pup && pup.chains.tail ? pup.chains.tail.points() : [{ x: 11, y: 28 }].concat(TAIL_REST.map((p) => ({ x: 11 + p.x, y: 28 + p.y })));
  const tailD = curve(tailPts);
  const tail = [stroke(tailD, '#e8dcff', 3.2), stroke(tailD, '#fffaf0', 1.4)];
  // legs hang from the body's underside; tucked legs fold up and inward
  const legY = FY - 3.6 - P.legTuck * 5 + P.bob * 0.5;
  const leg = (deg, x, side) => g([stroke(`M0 0 L0 ${3.2 - P.legTuck * 1.2}`, '#d8d0f4', 2.4), ell(0, 3.4 - P.legTuck * 1.2, 1.9, 1.2, '#eee8ff')], { transform: `${tr(x + side * P.legTuck * 1.5, legY)} ${rot(deg + side * P.legTuck * 25)}` });
  const legs = P.sit > 0.5 ? ell(18, FY - 1.5, 6, 1.6, '#d8d0f4') : [leg(P.legL, 15, -1), leg(P.legR, 21, 1)];
  // eyes: open/closed/squint and a glance direction
  const open = clamp(P.eyeOpen * (1 - P.squint * 0.75), 0, 1); const k = 1 + P.wide * 0.15;
  const eyes = P.squint > 0.6 && P.eyeOpen > 0.5 ? [stroke('M13.2 21.6 L16.6 21.2', '#3a2e55', 1.4), stroke('M19.4 21 L22.4 20.6', '#3a2e55', 1.4)]
    : [eye(15.2, 21, 2.1 * k, 2.9 * k, '#1a1526', true, open, P.look), eye(20.6, 20.4, 1.9 * k, 2.6 * k, '#1a1526', true, open, P.look)];
  // the paw: reaches to the wall when clinging, out and forward for a strike, holds the ember for a cast
  const px = 23, py = 27; const reach = P.paw * (P.pawKind === 'cling' ? -7 : P.pawKind === 'strike' ? 11 : 7); const a = P.pawAng * Math.PI / 180;
  const hx = px + Math.cos(a) * reach, hy = py + Math.sin(a) * reach;
  const paw = P.paw < 0.05 || P.pawKind === 'none' ? null
    : P.pawKind === 'cling' ? stroke(`M12 24 L${8 - P.paw * 0.5} ${18 + (1 - P.paw) * 5}`, '#f4ecff', 2.6)
    : P.pawKind === 'strike' ? [stroke(`M${px} ${py} L${hx} ${hy}`, '#f4ecff', 2.6), stroke(`M${hx} ${hy} L${hx + Math.cos(a) * 4} ${hy + Math.sin(a) * 4}`, '#ffe9b0', 1.8), stroke(`M${hx - Math.sin(a)} ${hy + Math.cos(a)} L${hx + Math.cos(a) * 4 - Math.sin(a)} ${hy + Math.sin(a) * 4 + Math.cos(a)}`, '#ffb347', 0.8, { opacity: 0.8 })]
    : [stroke(`M${px} ${py} L${hx} ${hy}`, '#f4ecff', 2.6), P.ember > 0.02 ? [circ(hx + Math.cos(a) * 1.5, hy + Math.sin(a) * 1.5, 4.5 * P.ember, '#ffb347', { opacity: 0.3 }), circ(hx + Math.cos(a) * 1.5, hy + Math.sin(a) * 1.5, 2.4 * P.ember, '#ffb347'), circ(hx + Math.cos(a) * 1.5, hy + Math.sin(a) * 1.5, 1.1 * P.ember, '#fff4dc')] : null];
  const bodyEl = path('M18 12 C25.5 12 27 19.5 26.2 27 C25.5 33 22.5 36.2 18 36.2 C13.5 36.2 10.5 33 9.8 27 C9 19.5 10.5 12 18 12 Z', bodyFill, { stroke: mix('#cbbde8', '#d08080', P.hurt), strokeWidth: 0.9 });
  const rim = stroke('M12.2 16 C13 13.8 15 12.6 17.5 12.4', '#ffffff', 1.2, { opacity: 0.8 });
  const shadow = path('M20 35.6 C24 34.5 26 30 25.6 25', '#8f7fbf', { opacity: 0.22 });
  const cheek = circ(23.6, 24.6, 1.6, '#ffc6b0', { opacity: P.cheek });
  const inner = circ(17, 21, 9 + P.glow * 6, rad('mc', 17, 21, 9 + P.glow * 6, [[0, '#ffffff', 0.5 + P.glow], [1, '#ffffff', 0]]));
  const aura = P.aura > 0.02 ? glow(18, 22, 17 + P.aura * 4, '#ffd080', 0.45 * P.aura) : null;
  const body = g([tail, ear(P.earL, 15.5, 12.5), bodyEl, inner, rim, shadow, cheek, ear(P.earR, 20, 12.2), eyes, paw], { transform: `${tr(FX, FY)} ${rot(P.lean)} scale(${P.sx} ${P.sy}) ${tr(-FX, -FY - P.bob)}` });
  return svg(W, H, [aura, body, legs]);
}

// ---- animation: from the player's state to parameter targets, every frame
function control(p, pup, info) {
  const dt = info.dt, m = pup.mem, t = pup.time;
  if (m.init === undefined) { m.init = true; m.air = !p.onGround; m.attackTimer = 0; m.castTimer = 0; m.blink = 2 + Math.random() * 3; m.glance = 1 + Math.random() * 3; m.lookTo = 0.3; m.hp = p.hp; m.wall = 0; m.dashT = 0; m.focusT = 0; }
  const tail = pup.chain('tail', 11, 28, TAIL_REST);
  const speed = Math.abs(p.vx) / RUN; const moving = p.onGround && Math.abs(p.vx) > 20;
  // events, found by watching the state change
  const landed = p.onGround && m.air, jumped = !p.onGround && !m.air; const struck = p.attackTimer > m.attackTimer, cast = p.castTimer > m.castTimer, hit = p.hp < m.hp;
  const dashStart = p.dashing > 0 && !m.dashing; m.dashing = p.dashing > 0;
  m.air = !p.onGround; m.attackTimer = p.attackTimer; m.castTimer = p.castTimer; m.hp = p.hp;
  if (landed) { pup.impulse('sy', -3.2).impulse('sx', 2.2).impulse('earL', 360).impulse('earR', 360).impulse('legTuck', -2); m.landT = 0.25; }
  if (jumped && p.vy < -150) { pup.impulse('sy', 2.4).impulse('sx', -1.4).impulse('earL', -420).impulse('earR', -420); }
  if (hit) pup.impulse('lean', -260).impulse('earL', 260).impulse('earR', -200);
  if (dashStart) pup.impulse('earCurl', 8);
  const T = { pawKind: 'none', paw: 0, ember: 0, aura: 0, hurt: 0, sit: 0, squint: 0, wide: 0, legTuck: 0, earCurl: 0, cheek: 0.45, glow: p.focusing || p.warm ? 0.5 : 0.28, bob: 0 };
  let eyeOpen = 1;
  // ---- blinks and glances (idle life)
  m.blink -= dt; if (m.blink < 0) { m.blink = (Math.random() < 0.2 ? 0.25 : 2.5 + Math.random() * 3); m.blinkT = 0.14; }
  if (m.blinkT > 0) { m.blinkT -= dt; eyeOpen = m.blinkT > 0.07 ? 1 - (0.14 - m.blinkT) / 0.07 : m.blinkT / 0.07; }
  m.glance -= dt; if (m.glance < 0) { m.glance = 1.5 + Math.random() * 3.5; m.lookTo = Math.random() < 0.5 ? 0.35 : -0.2 + Math.random() * 0.4; }
  T.look = moving || !p.onGround ? 0.45 : m.lookTo;
  // ---- base pose by state (priority order matches the old pose table)
  if (p.sitting) { Object.assign(T, { lean: 0, earL: -48 + Math.sin(t * 1.3) * 2, earR: -30 + Math.sin(t * 1.3 + 1) * 2, legL: 0, legR: 0, sit: 1, sx: 1.08 + Math.sin(t * 1.6) * 0.012, sy: 0.9 + Math.sin(t * 1.6) * 0.015 }); eyeOpen = Math.min(eyeOpen, Math.max(0, 1 - (p.benchTimer || 0) * 1.5)); }
  else if (p.hurtTimer > 0) { Object.assign(T, { lean: -10, earL: -30, earR: -46, legL: 20, legR: -20, squint: 1, hurt: 1, sx: 1.04, sy: 0.96 }); }
  else if (p.dashing > 0) { Object.assign(T, { lean: 22, earL: -92, earR: -74, earCurl: 1, legL: -30, legR: -30, legTuck: 0.5, squint: 1, sx: 1.28, sy: 0.74 }); }
  else if (p.focusing) { const k = p.focusTimer / 0.9; Object.assign(T, { lean: 0, earL: -20 + k * 14, earR: 2 + k * 14, legL: 0, legR: 0, aura: 0.4 + k * 0.6, glow: 0.6 + k * 0.4, sx: 1.03 + Math.sin(t * 5) * 0.012, sy: 0.97 + Math.sin(t * 5) * 0.02, bob: k * 1.5, cheek: 0.6 }); eyeOpen = 0; }
  else if (p.wallSliding) { Object.assign(T, { lean: -14, earL: -20 + Math.sin(t * 9) * 3, earR: 6 + Math.sin(t * 9 + 2) * 3, legL: 30, legR: 20, paw: 1, pawKind: 'cling', sx: 0.96, sy: 1.02 }); }
  else if (!p.onGround) {
    const up = p.vy < -60, fall = p.vy > 120; const vk = clamp(p.vy / 430, -1, 1);
    Object.assign(T, { lean: clamp(p.vx / 400, -1, 1) * 10 + (up ? 5 : -3), earL: up ? -78 : fall ? -8 - vk * 6 : -40, earR: up ? -56 : fall ? 14 : -18, legL: up ? -40 : 14, legR: up ? -40 : -10, legTuck: up ? 0.7 : 0.15, wide: fall ? 1 : 0, sx: up ? 0.92 : 1.04, sy: up ? 1.14 : 0.96, earCurl: fall ? 0.4 : 0 });
    if (p.canDoubleJump === false && up) T.lean += 6; // second leap: a little more flourish
  }
  else if (moving) {
    // a bounding gait: crouch, spring forward with the legs trailing, land on them again; one bound per 4 units of the
    // run counter (that is also the footstep cadence), amplitude scaled by speed so a slow walk is a gentle shuffle
    const ph = p.anim.run * (Math.PI / 2); const s = Math.sin(ph), c = Math.cos(ph); const back = Math.sign(p.vx) !== p.facing ? -1 : 1;
    Object.assign(T, { lean: (8 + s * 7) * speed * back, earL: -40 - speed * 22 + s * 9 * speed, earR: -14 - speed * 22 + s * 9 * speed, legL: (-c * 30 - 4) * speed * back, legR: (-Math.cos(ph + 0.7) * 30 + 4) * speed * back,
      legTuck: Math.max(0, s) * 0.35 * speed, sy: 1 + s * 0.11 * speed, sx: 1 - s * 0.06 * speed, bob: Math.max(0, s) * 4.2 * speed });
  }
  else {
    m.twitch = (m.twitch === undefined ? 2 + Math.random() * 4 : m.twitch - dt); if (m.twitch < 0) { m.twitch = 2.5 + Math.random() * 5; pup.impulse(Math.random() < 0.5 ? 'earL' : 'earR', 260); }
    Object.assign(T, { lean: 0, earL: -38 + Math.sin(t * 1.7) * 2.5, earR: -14 + Math.sin(t * 1.7 + 0.9) * 2.5, legL: 0, legR: 0, sx: 1 + Math.sin(t * 2.2) * 0.012, sy: 1 + Math.sin(t * 2.2) * 0.018 });
  }
  // ---- actions layered on top: strike and cast clips keyed to the player's own timers
  if (p.attackTimer > 0 && !p.dashing) {
    const k = 1 - p.attackTimer / 0.11; const dirA = p.attackDir === 'up' ? -95 : p.attackDir === 'down' ? 75 : -18;
    const c = Anim.keys(k, [[0, { paw: 0.2, lean: -4 }], [0.35, { paw: 1.25, lean: 16 }, 'outCubic'], [1, { paw: 0.9, lean: 10 }, 'outQuad']]);
    Object.assign(T, { pawKind: 'strike', paw: c.paw, pawAng: dirA, lean: T.lean + c.lean, earL: T.earL - 30, earR: T.earR - 30, squint: 1 });
    if (struck) pup.impulse('sx', 1.6).impulse('earL', -200).impulse('earR', -200);
  } else if (p.castTimer > 0) {
    const k = 1 - p.castTimer / 0.35;
    const c = Anim.keys(k, [[0, { paw: 0.3, ember: 1, lean: -6 }], [0.25, { paw: 0.5, ember: 1.2, lean: -8 }, 'outQuad'], [0.4, { paw: 1.2, ember: 0, lean: 12 }, 'outCubic'], [1, { paw: 0.6, ember: 0, lean: 4 }, 'outQuad']]);
    Object.assign(T, { pawKind: 'ember', paw: c.paw, pawAng: -25, ember: c.ember, lean: T.lean + c.lean, earL: T.earL - 20, earR: T.earR - 20 });
    if (cast) pup.impulse('sx', -1.5).impulse('sy', 1.5);
  }
  if (p.flareCd > 1.85) { T.glow = 1; T.aura = 1; T.earL = -70; T.earR = -50; }
  T.eyeOpen = eyeOpen;
  pup.target(T);
  // ---- secondary motion: the tail streams behind the body, flutters when idle, hangs when clinging
  const vxs = p.vx / SCALE, vys = p.vy / SCALE; const facing = p.wallSliding ? -p.wallDir : p.facing;
  tail.update(dt, { vx: vxs * 0.35, vy: vys * 0.25, facing, gravity: p.wallSliding ? 90 : 26, drag: 0.5, stiff: p.onGround && !moving ? 9 : 5, damp: 0.86, wind: { x: Math.sin(t * 2.6) * 6 * (moving ? 0 : 1), y: Math.cos(t * 1.9) * 4 } });
  // dash after-images
  if (p.dashing > 0) { m.ghostT = (m.ghostT || 0) + dt; if (m.ghostT > 0.022) { m.ghostT = 0; pup.ghost(p.x + p.w / 2, p.y + p.h, 0.3, 0.5); } }
}

module.exports = { name: 'mote', w: W, h: H, anchor: 'bottom', params, springs, poses, make, control };

});
define("backgrounds", function (module, exports, require) {
// Painted parallax layers, two per area, tiling horizontally at 1024 px.
const L = require('./lib');
const { svg, lin, rad, path, ell, circ, rect, stroke, g, rng } = L;
const W = 1024, H = 640;
const sheet = {}; const add = (name, fn) => { sheet[name] = { w: W, h: H, anchor: 'topleft', make: fn }; };
// draw a shape three times so it wraps seamlessly across the 1024 px seam
const wrap = (el, x) => [-W, 0, W].map((o) => g([el], { transform: `translate(${o} 0)` })).join('');
const fog = (id, color, a) => rad(id, 0, 0, 1, [[0, color, a], [1, color, 0]]);

// ---- Rootshade: the underside of the sleeping tree, roots as thick as houses
add('bg_rootshade_far', () => {
  const r = rng(101); const out = []; const defs = lin('rsf', 0, 0, 0, H, [[0, '#2a2648'], [1, '#191632']]);
  for (let i = 0; i < 9; i++) { const x = r() * W, w = 40 + r() * 70, len = 260 + r() * 300, sway = (r() - 0.5) * 120; out.push(wrap(path(`M${x - w / 2} -10 C${x - w / 2 + sway * 0.3} ${len * 0.4} ${x + sway - w * 0.2} ${len * 0.8} ${x + sway} ${len} C${x + sway + w * 0.2} ${len * 0.8} ${x + w / 2 + sway * 0.3} ${len * 0.4} ${x + w / 2} -10 Z`, 'url(#rsf)', { opacity: 0.85 }))); }
  for (let i = 0; i < 30; i++) { const x = r() * W, y = 60 + r() * 500; out.push(wrap(circ(x, y, 1.2 + r() * 1.6, '#b8b0e0', { opacity: 0.15 + r() * 0.2 }))); }
  return svg(W, H, out.join(''), defs);
});
add('bg_rootshade_near', () => {
  const r = rng(102); const out = []; const defs = lin('rsn', 0, 0, 0, H, [[0, '#3a3558'], [1, '#221f3a']]);
  for (let i = 0; i < 6; i++) { const x = r() * W, w = 24 + r() * 40, len = 160 + r() * 260, sway = (r() - 0.5) * 80; out.push(wrap(path(`M${x - w / 2} -10 C${x - w / 2 + sway * 0.4} ${len * 0.5} ${x + sway - w * 0.15} ${len * 0.85} ${x + sway} ${len} C${x + sway + w * 0.15} ${len * 0.85} ${x + w / 2 + sway * 0.4} ${len * 0.5} ${x + w / 2} -10 Z`, 'url(#rsn)'))); for (let k = 0; k < 3; k++) { const t = 0.3 + r() * 0.6; out.push(wrap(stroke(`M${x + sway * t - w * 0.3} ${len * t} c${-20 - r() * 30} ${10 + r() * 30} ${-10} ${40 + r() * 40} ${-30 - r() * 20} ${60 + r() * 50}`, '#2c2848', 3 + r() * 3, { opacity: 0.9 }))); } }
  for (let i = 0; i < 7; i++) { const x = r() * W, y = 420 + r() * 220, w = 80 + r() * 160, h = 60 + r() * 120; out.push(wrap(path(`M${x - w / 2} ${H + 10} C${x - w / 2} ${y + h * 0.4} ${x - w * 0.2} ${y} ${x} ${y} C${x + w * 0.2} ${y} ${x + w / 2} ${y + h * 0.4} ${x + w / 2} ${H + 10} Z`, '#2a2646', { opacity: 0.95 }))); }
  return svg(W, H, out.join(''), defs);
});

// ---- Fernwake: fronds the size of sails, spores drifting up
const frond = (x, y, len, ang, color, r) => { const els = []; const ca = Math.cos(ang), sa = Math.sin(ang); const tipx = x + ca * len, tipy = y + sa * len; els.push(stroke(`M${x} ${y} Q${x + ca * len * 0.5 - sa * 30} ${y + sa * len * 0.5 + ca * 30} ${tipx} ${tipy}`, color, 3 + len * 0.02)); for (let k = 1; k < 9; k++) { const t = k / 9; const px = x + ca * len * t - sa * 30 * (1 - Math.abs(t - 0.5) * 2) * 0.5, py = y + sa * len * t + ca * 30 * (1 - Math.abs(t - 0.5) * 2) * 0.5; const ll = (1 - t) * len * 0.28 + 6; els.push(path(`M${px} ${py} Q${px - sa * ll * 0.7 - ca * ll * 0.2} ${py + ca * ll * 0.7 - sa * ll * 0.2} ${px - sa * ll * 1.1 + ca * ll * 0.5} ${py + ca * ll * 1.1 + sa * ll * 0.5} Q${px - sa * ll * 0.3 + ca * ll * 0.5} ${py + ca * ll * 0.3 + sa * ll * 0.5} ${px} ${py} Z`, color)); els.push(path(`M${px} ${py} Q${px + sa * ll * 0.7 - ca * ll * 0.2} ${py - ca * ll * 0.7 - sa * ll * 0.2} ${px + sa * ll * 1.1 + ca * ll * 0.5} ${py - ca * ll * 1.1 + sa * ll * 0.5} Q${px + sa * ll * 0.3 + ca * ll * 0.5} ${py - ca * ll * 0.3 + sa * ll * 0.5} ${px} ${py} Z`, color)); } return els.join(''); };
add('bg_fernwake_far', () => {
  const r = rng(201); const out = [];
  for (let i = 0; i < 10; i++) { const x = r() * W, y = H + 20; const ang = -Math.PI / 2 + (r() - 0.5) * 1.2; out.push(wrap(frond(x, y, 220 + r() * 220, ang, '#1e3a2a', r))); }
  for (let i = 0; i < 40; i++) out.push(wrap(circ(r() * W, r() * H, 1 + r() * 1.8, '#9be05f', { opacity: 0.12 + r() * 0.25 })));
  return svg(W, H, out.join(''));
});
add('bg_fernwake_near', () => {
  const r = rng(202); const out = [];
  for (let i = 0; i < 7; i++) { const x = r() * W, y = H + 30; const ang = -Math.PI / 2 + (r() - 0.5) * 1.4; out.push(wrap(frond(x, y, 320 + r() * 260, ang, i % 2 ? '#26482f' : '#1c3826', r))); }
  for (let i = 0; i < 8; i++) { const x = r() * W, y = r() * 200; out.push(wrap(stroke(`M${x} -10 C${x + (r() - 0.5) * 60} ${y + 80} ${x + (r() - 0.5) * 80} ${y + 160} ${x + (r() - 0.5) * 40} ${y + 260}`, '#2e5a34', 4 + r() * 4))); }
  return svg(W, H, out.join(''));
});

// ---- The Drownwell: drowned arches and weed, light wavering down through water
add('bg_drownwell_far', () => {
  const r = rng(301); const out = []; const defs = lin('dwf', 0, 0, 0, H, [[0, '#1a3050'], [1, '#0c1a2c']]);
  for (let i = 0; i < 7; i++) { const x = r() * W, w = 90 + r() * 120, y = 220 + r() * 260, h = 160 + r() * 240; out.push(wrap(path(`M${x - w / 2} ${H + 10} L${x - w / 2} ${y + h * 0.35} C${x - w / 2} ${y} ${x + w / 2} ${y} ${x + w / 2} ${y + h * 0.35} L${x + w / 2} ${H + 10} Z`, 'url(#dwf)', { opacity: 0.9 }))); out.push(wrap(path(`M${x - w * 0.32} ${H + 10} L${x - w * 0.32} ${y + h * 0.45} C${x - w * 0.32} ${y + h * 0.15} ${x + w * 0.32} ${y + h * 0.15} ${x + w * 0.32} ${y + h * 0.45} L${x + w * 0.32} ${H + 10} Z`, '#0a1626'))); }
  for (let i = 0; i < 6; i++) { const x = r() * W; out.push(wrap(path(`M${x - 40} -10 L${x + 40} -10 L${x + 90 + r() * 60} ${H} L${x - 90 - r() * 60} ${H} Z`, '#3a6a9a', { opacity: 0.05 + r() * 0.05 }))); }
  return svg(W, H, out.join(''), defs);
});
add('bg_drownwell_near', () => {
  const r = rng(302); const out = [];
  for (let i = 0; i < 16; i++) { const x = r() * W, len = 80 + r() * 260; out.push(wrap(stroke(`M${x} -10 C${x + (r() - 0.5) * 40} ${len * 0.4} ${x - (r() - 0.5) * 60} ${len * 0.7} ${x + (r() - 0.5) * 50} ${len}`, i % 3 ? '#16324a' : '#1e4460', 3 + r() * 5))); }
  for (let i = 0; i < 5; i++) { const x = r() * W, w = 30 + r() * 50, y = 300 + r() * 200; out.push(wrap(rect(x - w / 2, y, w, H - y + 10, '#0f2438', { rx: 3 }))); out.push(wrap(rect(x - w / 2 - 6, y - 8, w + 12, 10, '#163048', { rx: 2 }))); }
  for (let i = 0; i < 24; i++) out.push(wrap(circ(r() * W, r() * H, 1.5 + r() * 2.5, '#8ce0ff', { opacity: 0.08 + r() * 0.15 })));
  return svg(W, H, out.join(''));
});

// ---- Chimeglass Reach: spires of glass that ring when the wind moves
const spire = (x, y, w, h, c1, c2, o = 1) => path(`M${x - w / 2} ${y} L${x} ${y - h} L${x + w / 2} ${y} Z`, c1, { opacity: o }) + path(`M${x} ${y - h} L${x + w / 2} ${y} L${x + w * 0.1} ${y} Z`, c2, { opacity: o * 0.7 });
add('bg_chimeglass_far', () => {
  const r = rng(401); const out = [];
  for (let i = 0; i < 14; i++) { const x = r() * W, h = 160 + r() * 380, w = 30 + r() * 60; out.push(wrap(spire(x, H + 10, w, h, '#2e2446', '#3f3260', 0.9))); }
  for (let i = 0; i < 10; i++) { const x = r() * W, h = 100 + r() * 200, w = 20 + r() * 40; out.push(wrap(g([spire(x, -10, w, h, '#2e2446', '#3f3260', 0.85)], { transform: `translate(${x} ${-10}) scale(1 -1) translate(${-x} ${10})` }))); }
  for (let i = 0; i < 30; i++) out.push(wrap(circ(r() * W, r() * H, 1 + r() * 1.5, '#e6d3ff', { opacity: 0.1 + r() * 0.3 })));
  return svg(W, H, out.join(''));
});
add('bg_chimeglass_near', () => {
  const r = rng(402); const out = [];
  for (let i = 0; i < 9; i++) { const x = r() * W, h = 220 + r() * 320, w = 44 + r() * 70; out.push(wrap(spire(x, H + 10, w, h, '#3a2d58', '#5a4a80'))); const gl = L.glow(x, H - h * 0.5, 40 + r() * 40, '#c9a0ff', 0.12); out.push(gl.def + wrap(gl.el)); }
  for (let i = 0; i < 12; i++) { const x = r() * W, y = H - r() * 120, s = 10 + r() * 20; out.push(wrap(path(`M${x - s * 0.6} ${y} L${x} ${y - s * 2} L${x + s * 0.6} ${y} Z`, '#8a6ac0', { opacity: 0.9 }))); }
  return svg(W, H, out.join(''));
});

// ---- Bramblehush: thorn tangles and a thicket that grew over the road
const bramble = (x, y, len, r, color, w) => { let d = `M${x} ${y}`; let cx = x, cy = y; const els = []; for (let k = 0; k < 6; k++) { const nx = cx + (r() - 0.5) * len * 0.5, ny = cy - len * 0.16 - r() * 20; d += ` Q${cx + (r() - 0.5) * 40} ${cy - 10} ${nx} ${ny}`; if (k % 2) els.push(path(`M${nx} ${ny} l${4 + r() * 4} ${-6 - r() * 6} l${2} ${8} Z`, color)); cx = nx; cy = ny; } els.unshift(stroke(d, color, w)); return els.join(''); };
add('bg_bramblehush_far', () => {
  const r = rng(501); const out = []; const defs = lin('bhf', 0, 0, 0, H, [[0, '#1c261a'], [1, '#101610']]);
  for (let i = 0; i < 12; i++) { const x = r() * W; out.push(wrap(bramble(x, H + 10, 280 + r() * 260, r, '#1c2a1c', 6 + r() * 6))); }
  for (let i = 0; i < 6; i++) { const x = r() * W, w = 120 + r() * 200; out.push(wrap(path(`M${x - w / 2} ${H + 10} C${x - w / 4} ${H - 120 - r() * 150} ${x + w / 4} ${H - 120 - r() * 150} ${x + w / 2} ${H + 10} Z`, 'url(#bhf)'))); }
  return svg(W, H, out.join(''), defs);
});
add('bg_bramblehush_near', () => {
  const r = rng(502); const out = [];
  for (let i = 0; i < 9; i++) { const x = r() * W; out.push(wrap(bramble(x, H + 10, 320 + r() * 300, r, '#25381f', 8 + r() * 8))); }
  for (let i = 0; i < 9; i++) { const x = r() * W; out.push(wrap(bramble(x, -10, -(200 + r() * 200), r, '#1e2e1a', 6 + r() * 6))); }
  for (let i = 0; i < 18; i++) out.push(wrap(circ(r() * W, r() * H, 1 + r() * 1.5, '#c4d070', { opacity: 0.1 + r() * 0.25 })));
  return svg(W, H, out.join(''));
});

// ---- Puffcap Warrens: mushrooms like cathedrals, spores like snow
const cap = (x, y, w, h, c1, c2) => path(`M${x - w / 2} ${y} C${x - w / 2} ${y - h} ${x + w / 2} ${y - h} ${x + w / 2} ${y} C${x + w * 0.3} ${y - h * 0.15} ${x - w * 0.3} ${y - h * 0.15} ${x - w / 2} ${y} Z`, c1) + path(`M${x - w * 0.2} ${y - h * 0.86} C${x} ${y - h * 0.98} ${x + w * 0.2} ${y - h * 0.9} ${x + w * 0.25} ${y - h * 0.8}`, 'none', { stroke: c2, strokeWidth: 3, strokeLinecap: 'round', opacity: 0.6 });
add('bg_puffcap_far', () => {
  const r = rng(601); const out = [];
  for (let i = 0; i < 9; i++) { const x = r() * W, w = 120 + r() * 200, h = 60 + r() * 90, y = H - 100 - r() * 300; out.push(wrap(rect(x - w * 0.09, y - 2, w * 0.18, H - y + 10, '#2a2038'))); out.push(wrap(cap(x, y, w, h, '#3a2a4a', '#6a4a80'))); }
  for (let i = 0; i < 40; i++) out.push(wrap(circ(r() * W, r() * H, 1 + r() * 2, '#e0a8ff', { opacity: 0.1 + r() * 0.25 })));
  return svg(W, H, out.join(''));
});
add('bg_puffcap_near', () => {
  const r = rng(602); const out = [];
  for (let i = 0; i < 6; i++) { const x = r() * W, w = 200 + r() * 260, h = 90 + r() * 120, y = H - 40 - r() * 200; out.push(wrap(rect(x - w * 0.08, y - 2, w * 0.16, H - y + 10, '#33254a'))); out.push(wrap(cap(x, y, w, h, '#4a3260', '#8a5aa8'))); const gl = L.glow(x, y - h * 0.5, w * 0.5, '#d9a0f0', 0.1); out.push(gl.def + wrap(gl.el)); }
  for (let i = 0; i < 14; i++) { const x = r() * W, y = H - r() * 60; out.push(wrap(cap(x, y, 16 + r() * 24, 10 + r() * 14, '#c87ab8', '#ffd0f0'))); }
  return svg(W, H, out.join(''));
});

// ---- The Lanternry: the lamplighters' rooftops, most windows dark now
add('bg_lanternry_far', () => {
  const r = rng(701); const out = []; const defs = lin('lnf', 0, 0, 0, H, [[0, '#2a3454'], [1, '#161c30']]);
  for (let i = 0; i < 16; i++) { const x = r() * W, w = 50 + r() * 90, h = 120 + r() * 260, y = H - h; out.push(wrap(rect(x - w / 2, y, w, h + 10, 'url(#lnf)'))); out.push(wrap(path(`M${x - w / 2 - 6} ${y} L${x} ${y - 20 - r() * 30} L${x + w / 2 + 6} ${y} Z`, '#1c2440'))); if (r() < 0.5) out.push(wrap(rect(x + w * 0.2, y - 40, 8, 40, '#1c2440'))); for (let k = 0; k < 6; k++) { const wx = x - w / 2 + 10 + r() * (w - 20), wy = y + 20 + r() * (h - 40); const lit = r() < 0.18; out.push(wrap(rect(wx, wy, 6, 8, lit ? '#ffe0a0' : '#0e1220', { opacity: lit ? 0.7 : 1 }))); } }
  return svg(W, H, out.join(''), defs);
});
add('bg_lanternry_near', () => {
  const r = rng(702); const out = [];
  for (let i = 0; i < 5; i++) { const x = r() * W, y = 80 + r() * 160; const x2 = x + 200 + r() * 200; out.push(wrap(stroke(`M${x} ${y} Q${(x + x2) / 2} ${y + 60} ${x2} ${y + (r() - 0.5) * 40}`, '#1a1f33', 2))); for (let k = 1; k < 4; k++) { const t = k / 4; const lx = x + (x2 - x) * t, ly = y + 60 * 4 * t * (1 - t) * 0.5 + (r() - 0.5) * 10; out.push(wrap(stroke(`M${lx} ${ly} L${lx} ${ly + 14}`, '#1a1f33', 1.5))); const lit = r() < 0.4; out.push(wrap(rect(lx - 4, ly + 14, 8, 11, lit ? '#ffd27a' : '#2a2a3a', { rx: 1.5, opacity: lit ? 0.9 : 1 }))); if (lit) { const gl = L.glow(lx, ly + 19, 30, '#ffbe64', 0.25); out.push(gl.def + wrap(gl.el)); } } }
  for (let i = 0; i < 8; i++) { const x = r() * W, w = 90 + r() * 140, h = 200 + r() * 200; out.push(wrap(rect(x - w / 2, H - h, w, h + 10, '#20263e'))); out.push(wrap(path(`M${x - w / 2 - 8} ${H - h} L${x} ${H - h - 30 - r() * 30} L${x + w / 2 + 8} ${H - h} Z`, '#2a3050'))); }
  return svg(W, H, out.join(''));
});

// ---- Cinderthroat: columns of cooled ash and rivers of ember in the cracks
add('bg_cinderthroat_far', () => {
  const r = rng(801); const out = []; const defs = lin('ctf', 0, 0, 0, H, [[0, '#3a1c16'], [1, '#1c0c0a']]);
  for (let i = 0; i < 12; i++) { const x = r() * W, w = 50 + r() * 110, top = -10, h = 200 + r() * 460; out.push(wrap(path(`M${x - w / 2} ${top} L${x + w / 2} ${top} L${x + w * 0.35} ${top + h} L${x - w * 0.35} ${top + h} Z`, 'url(#ctf)', { opacity: 0.95 }))); }
  for (let i = 0; i < 14; i++) { const x = r() * W, y = 300 + r() * 340; out.push(wrap(stroke(`M${x} ${y} l${20 + r() * 40} ${-6 + r() * 12} l${20 + r() * 40} ${6 + r() * 12}`, '#ff6a2a', 1.5 + r() * 2, { opacity: 0.35 + r() * 0.35 }))); }
  return svg(W, H, out.join(''), defs);
});
add('bg_cinderthroat_near', () => {
  const r = rng(802); const out = [];
  for (let i = 0; i < 7; i++) { const x = r() * W, w = 80 + r() * 140, h = 260 + r() * 300; out.push(wrap(path(`M${x - w / 2} ${H + 10} L${x - w * 0.3} ${H - h} L${x + w * 0.3} ${H - h} L${x + w / 2} ${H + 10} Z`, '#2c1512'))); out.push(wrap(stroke(`M${x - w * 0.1} ${H - h + 20} L${x + (r() - 0.5) * 30} ${H - h * 0.5} L${x - (r() - 0.5) * 30} ${H}`, '#ff8a3c', 2, { opacity: 0.5 }))); const gl = L.glow(x, H - h * 0.4, 50 + r() * 50, '#ff6a2a', 0.12); out.push(gl.def + wrap(gl.el)); }
  for (let i = 0; i < 30; i++) out.push(wrap(circ(r() * W, r() * H, 0.8 + r() * 1.6, '#ffb070', { opacity: 0.15 + r() * 0.35 })));
  return svg(W, H, out.join(''));
});

module.exports = sheet;

});
  const mods = { lib: require('lib') };
  for (const k of ["mote","backgrounds"]) { try { mods[k] = require(k); } catch (e) { console.error('art module ' + k + ' failed: ' + e.message); } }
  return mods;
})();
